GET http://localhost:3000/product

###
GET http://localhost:3000/product/610ebf17917ea05e34715c7e

###
POST  http://localhost:3000/product
Content-Type: application/json

{
    "id_product": "2",
    "name": "Pasta Gigi President",
    "price": 24000,
    "category": "Produk Perawatan Badan",
    "stock": "15"
}

###
PATCH  http://localhost:3000/product/61109d50e39c4e1ea871422e
Content-Type: application/json

{
    "title": "Sabun Colek Higienis",
    "price": 32000
}

###
DELETE http://localhost:3000/product/61109d50e39c4e1ea871422e